name = "cobs"
description = "Consistent Overhead Byte Stuffing (COBS) encoder/decoder"
version = "1.1.0"

licenses = "MIT"
authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
website = "https://github.com/damaki/cobs"
tags = ["cobs", "spark", "embedded", "nostd"]
