on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
    branches:
      - master
  pull_request:        # - A pull-request is opened or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  build-and-test:
    strategy:
      fail-fast: false # Don't stop all the workflows when one of them fails.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1
        with:
          version: 1.2.0

      - name: Build
        run: alr build --validation

      - name: Unit tests
        run: |
          cd tests
          alr build --validation
          alr run

      - name: Proof
        run:
          cd prove
          alr exec -- gnatprove -P ../cobs.gpr
