name: CI

on: [push, pull_request]

jobs:
  gnat_ce_2020:
    name: gnat-community-2020
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GNAT Community 2020
        run: docker run -v $PWD:/app componolit/ci:gnat-community-2020 /bin/sh -c "gprbuild -p -P /app/cobs.gpr -j0"
  proof:
    name: proof
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Proof
        run: docker run -v $PWD:/app componolit/ci:gnat-community-2020 /bin/sh -c "gnatprove -P /app/cobs.gpr -j0 --level=1"