on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
    branches:
      - master
  pull_request:        # - A pull-request is opened or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  build-and-test:
    strategy:
      fail-fast: false # Don't stop all the workflows when one of them fails.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1
        with:
          version: 1.2.0

      - name: Build
        run: alr build --validation

      - name: Unit tests
        run: |
          cd tests
          alr build --validation
          alr run

      - name: Instrument the project for coverage analysis
        run: |
          cd tests
          alr gnatcov instrument --level=stmt+mcdc --dump-trigger=atexit --projects cobs.gpr

      - name: Build the tests with instrumented code
        run: |
          cd tests
          alr build --validation -- --src-subdirs=gnatcov-instr --implicit-with=gnatcov_rts_full

      - name: Run instrumented unit tests
        run: |
          cd tests
          alr exec -- bin/unit_tests

      - name: Run GNATcov code coverage analysis on the test files
        run: |
          cd tests
          alr gnatcov coverage --annotate=xcov --output-dir gnatcov_out --level=stmt+mcdc --projects cobs.gpr *srctrace

      - uses: alire-project/gnatcov-to-codecovio-action@main
        with:
          fail_ci_if_error: false # Don't fail the workflow if codecov.io failed
          verbose: true

      - name: Proof
        run: |
          cd prove
          alr exec -- gnatprove -P ../cobs.gpr
